[variables]
NIXPACKS_JDK_VERSION = "21"

[phases.setup]
nixPkgs = ["jdk21_headless", "maven", "postgresql"]

[phases.build]
cmds = ["mvn clean package -Dgpg.skip=true -Dmaven.javadoc.skip=true -DskipTests=true"]

[start]
cmd = "./railway-start.sh"
